### ISSUE TITLE
The experimental results are not reproducible. 

### ISSUE THREAD

**Issue by qmy0701** [yuqianghan/editretro#2]
I have removed the augmentation from the test set by setting the `augmentation` parameter to 1 and randomized the atom map numbers (the atom map numbers for USPTO-50K from https://github.com/Hanjun-Dai/GLN are actually in the canonical order of the reactant SMILES). Subsequently, we have observed a significant degradation in the model's performance. The results are depicted in the figure below. Could you please verify whether the correct checkpoint has been uploaded or if there is any potential for label leakage in your implementation? Thank you in advance for your assistance, and I look forward to your reply.

![04138bba38c33240b51ef3b06c67e66](https://github.com/user-attachments/assets/a9a037fe-dfa4-4ac8-bfe0-9b1e894ad7ef)

**Comment by yuqianghan** [comment]
Thank you for your interest in our work. I would like to highlight the importance of augmentation in our method, which is also employed in other sequence-based approaches [1,2]. Specifically, we utilize atom map numbers to align reactants and products, thereby reducing the editing distance between them. This preprocessing step is implemented by the baseline R-SMILES  [https://github.com/otori-bird/retrosynthesis/blob/main/preprocessing/generate_PtoR_data.py].

Upon reviewing the image, I noticed that there may be an issue with your settings. The original file length is 100140, which is subjected to 20x augmentations. However, the original target length is 250, which may indicate a mismatch between the predictions and the ground truth.

If needed, please feel free to share your settings, and I would be happy to help review them.


[1] Tetko, Igor V., et al. "State-of-the-art augmented NLP transformer models for direct and single-step retrosynthesis." Nature communications 11.1 (2020): 5575.
[2] Zhong, Zipeng, et al. "Root-aligned SMILES: a tight representation for chemical reaction prediction." Chemical Science 13.31 (2022): 9023-9034.

**Comment by zengkaipeng** [comment]
> Thank you for your interest in our work. I would like to highlight the importance of augmentation in our method, which is also employed in other sequence-based approaches [1,2]. Specifically, we utilize atom map numbers to align reactants and products, thereby reducing the editing distance between them. This preprocessing step is implemented by the baseline R-SMILES [https://github.com/otori-bird/retrosynthesis/blob/main/preprocessing/generate_PtoR_data.py].
> 
> Upon reviewing the image, I noticed that there may be an issue with your settings. The original file length is 100140, which is subjected to 20x augmentations. However, the original target length is 250, which may indicate a mismatch between the predictions and the ground truth.
> 
> If needed, please feel free to share your settings, and I would be happy to help review them.
> 
> [1] Tetko, Igor V., et al. "State-of-the-art augmented NLP transformer models for direct and single-step retrosynthesis." Nature communications 11.1 (2020): 5575. [2] Zhong, Zipeng, et al. "Root-aligned SMILES: a tight representation for chemical reaction prediction." Chemical Science 13.31 (2022): 9023-9034.

I have reviewed the input size of my dataset and the size of the model-generated results, and found that after preprocessing, the dataset contains 5007 entries, which is in accordance with the parameter settings. The number of rows in the generated answers is 10,040, which is also consistent with the results obtained from running the script. This is because, according to the reasoning script you provided, the `--repos-beam` is set to 5 and the `--token-beam` is set to 4, meaning that for each sample in the dataset, the model will produce 20 candidates, which is also consistent with the number of rows in the generated results. For specific statistical details, please refer to the figure attached below. Therefore, I believe there is no mismatch between the predictions and the ground truth.

Of course, for the convenience of communication and subsequent file transfer, it would be very pleasing if you could provide your email. I will then send you the test data with randomized atom mapping via email.



![微信图片_20240804124954](https://github.com/user-attachments/assets/cb78e1f6-a856-41ba-bef4-209d3a62bdbe)

**Comment by qmy0701** [comment]
> Thank you for your interest in our work. I would like to highlight the importance of augmentation in our method, which is also employed in other sequence-based approaches [1,2]. Specifically, we utilize atom map numbers to align reactants and products, thereby reducing the editing distance between them. This preprocessing step is implemented by the baseline R-SMILES [https://github.com/otori-bird/retrosynthesis/blob/main/preprocessing/generate_PtoR_data.py].
> 
> Upon reviewing the image, I noticed that there may be an issue with your settings. The original file length is 100140, which is subjected to 20x augmentations. However, the original target length is 250, which may indicate a mismatch between the predictions and the ground truth.
> 
> If needed, please feel free to share your settings, and I would be happy to help review them.
> 
> [1] Tetko, Igor V., et al. "State-of-the-art augmented NLP transformer models for direct and single-step retrosynthesis." Nature communications 11.1 (2020): 5575. [2] Zhong, Zipeng, et al. "Root-aligned SMILES: a tight representation for chemical reaction prediction." Chemical Science 13.31 (2022): 9023-9034.

I have reviewed the input size of my dataset and the size of the model-generated results, and found that after preprocessing, the dataset contains 5007 entries, which is in accordance with the parameter settings. The number of rows in the generated answers is 10,040, which is also consistent with the results obtained from running the script. This is because, according to the reasoning script you provided, the `--repos-beam` is set to 5 and the `--token-beam` is set to 4, meaning that for each sample in the dataset, the model will produce 20 candidates, which is also consistent with the number of rows in the generated results. For specific statistical details, please refer to the figure attached below. Therefore, I believe there is no mismatch between the predictions and the ground truth.

Of course, for the convenience of communication and subsequent file transfer, it would be very pleasing if you could provide your email. I will then send you the test data with randomized atom mapping via email.

![微信图片_20240804124954](https://github.com/user-attachments/assets/699033ba-e61a-4da0-8136-b6d036c8fae2)

**Comment by qmy0701** [comment]
> Thank you for your interest in our work. I would like to highlight the importance of augmentation in our method, which is also employed in other sequence-based approaches [1,2]. Specifically, we utilize atom map numbers to align reactants and products, thereby reducing the editing distance between them. This preprocessing step is implemented by the baseline R-SMILES [https://github.com/otori-bird/retrosynthesis/blob/main/preprocessing/generate_PtoR_data.py].
> 
> Upon reviewing the image, I noticed that there may be an issue with your settings. The original file length is 100140, which is subjected to 20x augmentations. However, the original target length is 250, which may indicate a mismatch between the predictions and the ground truth.
> 
> If needed, please feel free to share your settings, and I would be happy to help review them.
> 
> [1] Tetko, Igor V., et al. "State-of-the-art augmented NLP transformer models for direct and single-step retrosynthesis." Nature communications 11.1 (2020): 5575. [2] Zhong, Zipeng, et al. "Root-aligned SMILES: a tight representation for chemical reaction prediction." Chemical Science 13.31 (2022): 9023-9034.

Furthermore, it is reasonable to augment the training dataset, but it seems not so reasonable to augment the test dataset during inference, as in practice, people tend to use canonical SMILES for queries rather than using many variants. Using only canonical product SMILES for inference can eliminate any label leakage, because canonical product SMILES is only related to the product itself. However, the original atom mapping number provides the order of atoms in the canonical reactant SMILES, and if the atom mapping is not removed during the training process of the model, it will provide the target information to the model, thus causing label leakage. At the same time, the inference mentioned above uses the finetune_50k.pt checkpoint provided by the repository, and we have not retrained the model.

**Comment by yuqianghan** [comment]
You can send your generations.json and the raw test data to hyq2015@zju.edu.cn.  And we will check the results asap.

The augmentation of the test dataset is analogous to ensemble learning, where multiple variant source sequences are used to generate a diverse set of outputs. This approach has been shown to be effective in sequence-based methods, as demonstrated in the analysis presented in [1]. Furthermore, this strategy has been successfully employed in several subsequent studies, highlighting its utility in improving model performance. So in our sequence-based method, we also utilized this strategy.

Regarding atom mapping, please refer to Root-aligned SMILES [2] for more details, that introduces the concept of aligning the sequences of reactants and products according to their atom-mapping numbers. By doing so, they effectively provide the target information to the model, training it to generate sequences with the minimum edit distance to the input sequence. Their approach may draw inspiration from the alignment preprocessing techniques used in some NLP tasks with seq2seq framework. We have not found label leakage issues.

[1] Tetko, Igor V., et al. "State-of-the-art augmented NLP transformer models for direct and single-step retrosynthesis." Nature communications 11.1 (2020): 5575. 
[2] Zhong, Zipeng, et al. "Root-aligned SMILES: a tight representation for chemical reaction prediction." Chemical Science 13.31 (2022): 9023-9034.

**Comment by yuqianghan** [comment]
And welcome further discussions on the potential label leakage issue related to atom-mapping.

**Comment by yuzhou2333** [comment]
> > Thank you for your interest in our work. I would like to highlight the importance of augmentation in our method, which is also employed in other sequence-based approaches [1,2]. Specifically, we utilize atom map numbers to align reactants and products, thereby reducing the editing distance between them. This preprocessing step is implemented by the baseline R-SMILES [https://github.com/otori-bird/retrosynthesis/blob/main/preprocessing/generate_PtoR_data.py].
> > Upon reviewing the image, I noticed that there may be an issue with your settings. The original file length is 100140, which is subjected to 20x augmentations. However, the original target length is 250, which may indicate a mismatch between the predictions and the ground truth.
> > If needed, please feel free to share your settings, and I would be happy to help review them.
> > [1] Tetko, Igor V., et al. "State-of-the-art augmented NLP transformer models for direct and single-step retrosynthesis." Nature communications 11.1 (2020): 5575. [2] Zhong, Zipeng, et al. "Root-aligned SMILES: a tight representation for chemical reaction prediction." Chemical Science 13.31 (2022): 9023-9034.
> 
> Furthermore, it is reasonable to augment the training dataset, but it seems not so reasonable to augment the test dataset during inference, as in practice, people tend to use canonical SMILES for queries rather than using many variants. Using only canonical product SMILES for inference can eliminate any label leakage, because canonical product SMILES is only related to the product itself. However, the original atom mapping number provides the order of atoms in the canonical reactant SMILES, and if the atom mapping is not removed during the training process of the model, it will provide the target information to the model, thus causing label leakage. At the same time, the inference mentioned above uses the finetune_50k.pt checkpoint provided by the repository, and we have not retrained the model.

Hello,bro~.i meet some question about generate.sh,when i use the command sh ./scripts/2_generate.sh 0 the CUDA out of memory,what's your command about this that the code will run correctly~~

**Comment by yuzhou2333** [comment]
> I have removed the augmentation from the test set by setting the `augmentation` parameter to 1 and randomized the atom map numbers (the atom map numbers for USPTO-50K from https://github.com/Hanjun-Dai/GLN are actually in the canonical order of the reactant SMILES). Subsequently, we have observed a significant degradation in the model's performance. The results are depicted in the figure below. Could you please verify whether the correct checkpoint has been uploaded or if there is any potential for label leakage in your implementation? Thank you in advance for your assistance, and I look forward to your reply.
> 
> ![04138bba38c33240b51ef3b06c67e66](https://private-user-images.githubusercontent.com/162131242/354826833-a9a037fe-dfa4-4ac8-bfe0-9b1e894ad7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTY2NjQsIm5iZiI6MTcyMzg5NjM2NCwicGF0aCI6Ii8xNjIxMzEyNDIvMzU0ODI2ODMzLWE5YTAzN2ZlLWRmYTQtNGFjOC1iZmUwLTliMWU4OTRhZDdlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMjA2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGNjZjgxNDA0M2Y2YjBhNzZiYzdiOWZiYjY2ZmU1Y2U1NGQyNjI2MzQ4Nzk1YTI0MDIxMmYyNTMwN2UxNzVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oMCpfVL2V26FIjOwfvq23stgY3G_4_WcxuQXLxVwSUs)

Hello,bro~.i meet some question about generate.sh,when i use the command sh ./scripts/2_generate.sh 0 the CUDA out of memory,what's your command about this that the code will run correctly~~

**Comment by zengkaipeng** [comment]
> > I have removed the augmentation from the test set by setting the `augmentation` parameter to 1 and randomized the atom map numbers (the atom map numbers for USPTO-50K from https://github.com/Hanjun-Dai/GLN are actually in the canonical order of the reactant SMILES). Subsequently, we have observed a significant degradation in the model's performance. The results are depicted in the figure below. Could you please verify whether the correct checkpoint has been uploaded or if there is any potential for label leakage in your implementation? Thank you in advance for your assistance, and I look forward to your reply.
> > ![04138bba38c33240b51ef3b06c67e66](https://private-user-images.githubusercontent.com/162131242/354826833-a9a037fe-dfa4-4ac8-bfe0-9b1e894ad7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTY2NjQsIm5iZiI6MTcyMzg5NjM2NCwicGF0aCI6Ii8xNjIxMzEyNDIvMzU0ODI2ODMzLWE5YTAzN2ZlLWRmYTQtNGFjOC1iZmUwLTliMWU4OTRhZDdlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMjA2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGNjZjgxNDA0M2Y2YjBhNzZiYzdiOWZiYjY2ZmU1Y2U1NGQyNjI2MzQ4Nzk1YTI0MDIxMmYyNTMwN2UxNzVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oMCpfVL2V26FIjOwfvq23stgY3G_4_WcxuQXLxVwSUs)
> 
> Hello,bro~.i meet some question about generate.sh,when i use the command sh ./scripts/2_generate.sh 0 the CUDA out of memory,what's your command about this that the code will run correctly~~

Well, you should change the --maxlen to reduce the required CUDA memory size. Further more, if you change the time of augmentation, dont forget to change the value of variable `aug` in the shell.

**Comment by yuzhou2333** [comment]
> > > I have removed the augmentation from the test set by setting the `augmentation` parameter to 1 and randomized the atom map numbers (the atom map numbers for USPTO-50K from https://github.com/Hanjun-Dai/GLN are actually in the canonical order of the reactant SMILES). Subsequently, we have observed a significant degradation in the model's performance. The results are depicted in the figure below. Could you please verify whether the correct checkpoint has been uploaded or if there is any potential for label leakage in your implementation? Thank you in advance for your assistance, and I look forward to your reply.
> > > ![04138bba38c33240b51ef3b06c67e66](https://private-user-images.githubusercontent.com/162131242/354826833-a9a037fe-dfa4-4ac8-bfe0-9b1e894ad7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTY2NjQsIm5iZiI6MTcyMzg5NjM2NCwicGF0aCI6Ii8xNjIxMzEyNDIvMzU0ODI2ODMzLWE5YTAzN2ZlLWRmYTQtNGFjOC1iZmUwLTliMWU4OTRhZDdlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMjA2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGNjZjgxNDA0M2Y2YjBhNzZiYzdiOWZiYjY2ZmU1Y2U1NGQyNjI2MzQ4Nzk1YTI0MDIxMmYyNTMwN2UxNzVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oMCpfVL2V26FIjOwfvq23stgY3G_4_WcxuQXLxVwSUs)
> > 
> > 
> > Hello,bro~.i meet some question about generate.sh,when i use the command sh ./scripts/2_generate.sh 0 the CUDA out of memory,what's your command about this that the code will run correctly~~
> 
> Well, you should change the `--max_token` to reduce the required CUDA memory size. Further more, if you change the time of augmentation, dont forget to change the value of variable `aug` in the shell.

Dear author,thank you for your answering~~,when i set the --max_token is 2500,the code can run correctly.

![image](https://github.com/user-attachments/assets/dcd6eb41-abd7-4fb2-86d5-12f56ca7051e)

The reproduced results are slightly worse than the results reported in the paper.All the code is run on a single 3090 GPU, with the commands executed in the following order:
bash ./scripts/0_pretrain.sh 0
bash ./scripts/1_finetune.sh 0
bash ./scripts/2_generate.sh 0

**Comment by zengkaipeng** [comment]
> > > > I have removed the augmentation from the test set by setting the `augmentation` parameter to 1 and randomized the atom map numbers (the atom map numbers for USPTO-50K from https://github.com/Hanjun-Dai/GLN are actually in the canonical order of the reactant SMILES). Subsequently, we have observed a significant degradation in the model's performance. The results are depicted in the figure below. Could you please verify whether the correct checkpoint has been uploaded or if there is any potential for label leakage in your implementation? Thank you in advance for your assistance, and I look forward to your reply.
> > > > ![04138bba38c33240b51ef3b06c67e66](https://private-user-images.githubusercontent.com/162131242/354826833-a9a037fe-dfa4-4ac8-bfe0-9b1e894ad7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTY2NjQsIm5iZiI6MTcyMzg5NjM2NCwicGF0aCI6Ii8xNjIxMzEyNDIvMzU0ODI2ODMzLWE5YTAzN2ZlLWRmYTQtNGFjOC1iZmUwLTliMWU4OTRhZDdlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxMjA2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGNjZjgxNDA0M2Y2YjBhNzZiYzdiOWZiYjY2ZmU1Y2U1NGQyNjI2MzQ4Nzk1YTI0MDIxMmYyNTMwN2UxNzVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oMCpfVL2V26FIjOwfvq23stgY3G_4_WcxuQXLxVwSUs)
> > > 
> > > 
> > > Hello,bro~.i meet some question about generate.sh,when i use the command sh ./scripts/2_generate.sh 0 the CUDA out of memory,what's your command about this that the code will run correctly~~
> > 
> > 
> > Well, you should change the `--max_token` to reduce the required CUDA memory size. Further more, if you change the time of augmentation, dont forget to change the value of variable `aug` in the shell.
> 
> Dear author,thank you for your answering~~,when i set the --max_token is 2500,the code can run correctly.
> 
> ![image](https://private-user-images.githubusercontent.com/74141246/359031636-dcd6eb41-abd7-4fb2-86d5-12f56ca7051e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjA1MDIsIm5iZiI6MTcyNDA2MDIwMiwicGF0aCI6Ii83NDE0MTI0Ni8zNTkwMzE2MzYtZGNkNmViNDEtYWJkNy00ZmIyLTg2ZDUtMTJmNTZjYTcwNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA5MzY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NzdmMTU0OWI1YzhiZTM5N2NmNDBiNWUxYjlkMGI0NGIzNmE1NmUxMTBjYjE5ODA0Mzk4M2U1NTIxM2IxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRltvT4dGNtrAVTx-btUlug5Y0RWTJ1v4IwceM8qxBU)
> 
> The reproduced results are slightly worse than the results reported in the paper.All the code is run on a single 3090 GPU, with the commands executed in the following order: bash ./scripts/0_pretrain.sh 0 bash ./scripts/1_finetune.sh 0 bash ./scripts/2_generate.sh 0

I'm not one of the authors, you might need to open an new issue for this.
