### ISSUE TITLE
如果要finetune大量数据，至少需要多大的显存，有推荐的显卡方案吗？

### ISSUE THREAD

**Issue by mspythontu** [yuqianghan/editretro#21]
您好！如果在checkpoint_full.pt的基础上继续finetune大量数据，至少需要多大的显存，有推荐的显卡方案吗？

**Comment by yuqianghan** [comment]
你好，Finetune 时候跟显存相关的参数是 max_tokens (*batch_size*)， 

1.  脚本里给的参数 A40 显存是够用的；
2. 如果想用 3090 或者 4090， 可以修改  max_tokens=20480, update=2  (两者乘积等于原来的 40960) 进行梯度累积；

以上两种方式没有改变 max_tokens，lr 无需修改。
如果你有更好的显卡可以使用，可以增大 max_tokens 同时增大 lr。
在大量数据集上微调该模型的时候，尽量保持较大的 max_tokens 可以提高模型训练的稳定性。

**Comment by mspythontu** [comment]
谢谢解答！

**Comment by mspythontu** [comment]
如果想要多卡分布式pretrain、finetune、generate和interactive，脚本中需要改哪些参数，谢谢！

**Comment by yuqianghan** [comment]
1. 在使用分布式进行 pretrain 和 finetune 时，需要修改 gpus 和 max_tokens，保证两者的乘积等于目前的 max_tokens，例如 gpus='0,1,2,3', max_tokens=10240.
2. generate 和 interactive 只支持单卡，这是使用的 fairseq 框架的限制。

**Comment by mspythontu** [comment]
明白了，thanks
