### ISSUE TITLE
how to use code like in the paper on multi-step retrosynthesis ?

### ISSUE THREAD

**Issue by thegodone** [yuqianghan/editretro#3]
In the paper you mentioned and shown results on retrosynthesis route design. 
EditRetro demonstrates practical utility in multi-step synthesis planning
To assess the practical utility of our one-step prediction method in synthesis planning, we extend EditRetro, which was trained on the USPTO-50K dataset, to enable the design of complete chemical pathways through sequential retrosynthetic predictions. 

Could you provide a code and instruction to run a single step retrosynthesis without reactant (tgt) but only product (src) ?

**Comment by thegodone** [comment]
I found by myself but this is very tricky, for the one that are at this stage, you need to use the data & model align to interactive model.

**Comment by yuqianghan** [comment]
Thank you for your interest in our work.  We have provided the necessary scripts in the _**interactive**_ folder. To generate candidates, simply place the product SMILES in the _**input_product.txt**_ file and update the _**model_path**_ variable to point to the desired model checkpoint file. Then, run the script using the command _**sh interactive/interactive_gen.sh**_. You can also modify various parameters within the script to generate different sets of candidates.

**Comment by thegodone** [comment]
great I came to the almost same conclusion. Thanks for the other users ;-)
