### ISSUE TITLE
The question about finetune

### ISSUE THREAD

**Issue by yuzhou2333** [yuqianghan/editretro#4]
Hello,dear author,when i reproduce this work,i use one GPU(3090). The pretain stage has no question,but when i start to finetune, there is a question that two variables have mismatched dimensions, which is causing the error.

![image](https://github.com/user-attachments/assets/0494dc7c-787e-4c72-9206-cb3d9e881701)

**Comment by yuqianghan** [comment]
Based on the figure, the error arises from a size mismatch between the ground-truth and the predictions of the reposition decoder.

1. Have you successfully installed Fairseq to utilize the GPU? If not, the code will run on the CPU, potentially leading to errors.  Please verify this first. You can check if a file named _fairseq/fairseq/libnat_cuda.cpython-310-x86_64-linux-gnu.so_ has been generated.

2. Have you made any changes to the settings?

Please inform me if you are still unable to resolve this issue.

**Comment by yuzhou2333** [comment]
Thank you for you response~~

The gpus,first parameter i set 0,that is mean the first gpu.
both "sh ./scripts/1_finetune.sh" and "sh ./scripts/1_finetune.sh 1"cause question,i think is there "gpus=$1".
![image](https://github.com/user-attachments/assets/02eccff3-1a9b-4e0f-8f5a-886c0ca60169)
This picture can prove that when i run the command "sh ./scripts/1_finetune.sh 0",the GPU has been used.

![image](https://github.com/user-attachments/assets/006d2cfb-40ae-4454-9550-003f8b40fca0)
the libnat_cuda.cpython-310-x86_64-linux-gnu.so is not in the path but the libnat.cpython-38-x86_64-linux-gnu.so is in the path.

i'm sure that i didn't change anything except the filepath like dataset and the pretrainpath.

**Comment by yuzhou2333** [comment]
ok, i think it's the version mismatch.Thank you for your help~~
