### ISSUE TITLE
运行pretain时会出现bernoulli_scalar_cpu_ not implemented for Half 是什么原因

### ISSUE THREAD

**Issue by mspythontu** [yuqianghan/editretro#5]

**Comment by yuqianghan** [comment]
你好，出现这个问题是因为 fairseq 没有正确安装，cuda 版本需要 11.x, 安装完以后请确保在 fairseq/fairseq 文件夹下有类似 libnat_cuda.cpython-310-x86_64-linux-gnu.so 文件编译生成。

**Comment by mspythontu** [comment]
谢谢作者回答～请问一下您的cuda是用的11.6.0还是11.6.1还是11.6.2呢？

**Comment by yuqianghan** [comment]
我们是用的 11.6.0，只要能正常编译出 libnat_cuda.cpython-xxx 文件都是可以的

**Comment by yuqianghan** [comment]
有可能是 gcc 版本不兼容的原因。

sudo apt install re2c
sudo apt-get install ninja-build

这两条命令有正确执行安装么

**Comment by yuqianghan** [comment]
我们使用的是 gcc-9.4.0 版本

**Comment by mspythontu** [comment]
是没有链接gcc，已经成功安装，正在pretrain
